import type {
  Appointment,
  BabyLog,
  Category,
  Child,
  DashboardSnapshot,
  InventoryItem,
  Task,
  Transaction,
  UUID,
} from "./domain";

type TimestampFields = "createdAt" | "updatedAt";

export type InsertPayload<T, AutoGenerated extends keyof T = never> = Omit<
  T,
  AutoGenerated | TimestampFields
>;

export type UpdatePayload<T, Immutable extends keyof T = never> = Partial<
  Omit<T, Immutable | "createdAt">
>;

export type CreateTaskInput = InsertPayload<Task, "id">;
export type UpdateTaskInput = UpdatePayload<Task>;

export type CreateInventoryItemInput = InsertPayload<InventoryItem, "id">;
export type UpdateInventoryItemInput = UpdatePayload<InventoryItem>;

export type CreateChildInput = InsertPayload<Child, "id">;
export type CreateBabyLogInput = InsertPayload<BabyLog, "id">;

export type CreateAppointmentInput = InsertPayload<Appointment, "id">;
export type UpdateAppointmentInput = UpdatePayload<Appointment>;

export type CreateCategoryInput = InsertPayload<Category, "id">;
export type CreateTransactionInput = InsertPayload<Transaction, "id">;

export interface PaginatedResult<T> {
  rows: T[];
  total: number;
}

export interface DashboardApiResponse extends DashboardSnapshot {
  generatedAt: string;
}

export interface TaskFilter {
  status?: Task["status"][];
  taskType?: Task["taskType"];
  assignedTo?: UUID;
  from?: string;
  to?: string;
}

